erikamodas/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path("admin/", admin.site.urls),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path("inventory/", include('inventory.urls')),
    path('assign-location', views.assign_location, name='assign_location'),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # Products
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:product_id>', views.details, name='details'),
    path('<int:product_id>/edit', views.edit, name='edit'),
    # Transactions
    path('transactions/', views.transaction_index, name='transaction_index'),
    path('transactions/create', views.transaction_create, name='transaction_create'),
    path('ajax/transactions', views.ajax_transactions, name='ajax_transactions'),
    # Locations
    path('locations/', views.location_index, name='location_index'),
    path('locations/create', views.location_create, name='location_create'),
    path('locations/<int:location_id>/edit', views.location_edit, name='location_edit'),
    # Reports
    path('xls/transactions/', views.xls_transactions, name='xls_transactions'),
    path('xls/products/', views.xls_products, name='xls_products'),
]

inventory/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# Tipos de transacción
TRANSACTION_TYPES = {
    'E': 'Entrada',
    'S': 'Salida',
}

# CASCADE: elimina el producto
# PROTECT: lanza un error
# RESTRICT: Solo elimina sino existen productos
# SET_NULL: actualiza a valor nulo
# SET_DEFAULT: asigna valor por defecto

class Location(models.Model):
    name = models.CharField(max_length=255)
    isActive = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class CustomUser(AbstractUser):
    pass
    location = models.ForeignKey(Location, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.username


class Product(models.Model):
    name = models.CharField(max_length=255)
    stock = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TransactionCab(models.Model):
    date = models.DateField()
    comment = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.RESTRICT)
    
    class Meta:
        db_table="transactions_cab"


class TransactionDet(models.Model):
    cab = models.ForeignKey(TransactionCab, related_name="details", on_delete=models.CASCADE)
    type = models.CharField(max_length=1, choices=TRANSACTION_TYPES)
    location = models.ForeignKey(Location, models.RESTRICT)
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    amount = models.IntegerField(default=0)
    
    class Meta:
        db_table = "transactions_det"

inventory/forms.py
from .models import Location, Product, TransactionCab, TransactionDet, CustomUser
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.forms import inlineformset_factory


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email", "location")


class CustomUserAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email")

class CreateProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name']
        
class LocationForm(ModelForm):
    class Meta:
        model = Location
        fields = ['name']


class EditProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name']


class TransactionForm(ModelForm):
    class Meta:
        model = TransactionDet
        fields = ['cab', 'type', 'product', 'location', 'amount']
    # def save(self, *args, **kwargs):
        

TransactionInlineFormset = inlineformset_factory(
    TransactionCab,
    TransactionDet,
    form=TransactionForm,
    extra=2
)

inventory/views.py
import datetime
import json
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from inventory.forms import CreateProductForm, EditProductForm, LocationForm, TransactionInlineFormset
from .models import Location, Product, TransactionDet, TransactionCab, TRANSACTION_TYPES
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django_excel_response import ExcelResponse

def current_products(request):
    products = Product.objects.all()
    for product in products:
        if request.user.location is not None:
            stock = TransactionDet.objects.filter(
                location=request.user.location, product=product).aggregate(Sum('amount'))['amount__sum']
        else:
            stock = TransactionDet.objects.filter(
                product=product).aggregate(Sum('amount'))['amount__sum']
        if stock is None:
            product.stock = 0
        else:
            product.stock = stock
        product.save()
    return products

@login_required
def index(request):
    products = current_products(request)

    return render(
        request,
        'product_index.html',
        context={'products': products}
    )


@login_required
def details(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    return render(
        request,
        'details.html',
        context={'product': product}
    )


@login_required
def edit(request, product_id):
    errors = None
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = EditProductForm(request.POST, instance=product)
        form.save()
        return redirect('product:index')

    return render(
        request,
        'product_edit.html',
        {
            'product': product,
            'errors': errors
        }
    )


def create_first_transaction(request, product):
    transaction_cab = TransactionCab.objects.create(
        date=datetime.datetime.now(),
        comment="Stock inicial",
        created_by=request.user)
    transaction_cab.save()
    transaction_det = TransactionDet.objects.create(
        cab=transaction_cab,
        type='E',  # Entrada
        location=request.user.location,
        product=product,
        amount=request.POST['stock']
    )
    transaction_det.save()


@login_required
def create(request):
    errors = None
    if request.method == 'POST':
        form = CreateProductForm(request.POST)
        if form.is_valid():
            new_product = form.save()
            create_first_transaction(request, product=new_product)
            return redirect('product:index')
        else:
            errors = form.errors.as_data()
    else:
        form = CreateProductForm()

    return render(
        request,
        'product_create.html',
        {
            'form': form,
            'errors': errors
        }
    )


@login_required
def ajax_transactions(request):

    if request.user.location is None:
        cab = TransactionCab.objects.all()
    else:
        cab = TransactionCab.objects.distinct().filter(
            details__location=request.user.location)

    data = []
    for item in cab:
        data.append({
            'id': item.id,
            'date': item.date.strftime("%d/%m/%Y"),
            'comment': item.comment,
            'details': list(item.details.values("product__name", "type", "location__name", "amount")),
        })
    return JsonResponse({'data': data, 'transaction_types': TRANSACTION_TYPES}, safe=False)


@login_required
def transaction_index(request):
    return render(
        request,
        'transaction_index.html'
    )


def update_stock():
    products = Product.objects.all()
    for product in products:
        stock = TransactionDet.objects.filter(
            product=product).aggregate(Sum('amount'))['amount__sum']
        product.stock = stock
        product.save()


@login_required
def transaction_create(request):
    errors = None
    formset = TransactionInlineFormset()

    if request.method == 'POST':
        try:
            transaction_cab = TransactionCab.objects.create(
                date=request.POST['date'],
                comment=request.POST['comment'],
                created_by=request.user)
            transaction_cab.save()
            formset = TransactionInlineFormset(
                request.POST, instance=transaction_cab)
            if formset.is_valid():
                formset.save()

                update_stock()

                resp = {
                    'title': 'Completado!',
                    'text': 'La transacción fue procesada correctamente',
                    'icon': 'success'
                }
            else:
                resp = {
                    'title': 'Aviso!',
                    'text': 'La transacción no es válida para procesar, verifique los campos e intente nuevamente.',
                    'icon': 'warning',
                    'errors': formset.errors
                }
        except Exception as ex:
            print(ex)
            resp = {
                'title': 'Error!',
                'text': 'Ha ocurrido un error en el proceso',
                'icon': 'error',
                'error': str(ex)
            }

        return JsonResponse(resp)
    else:

        locations = Location.objects.all()
        products = Product.objects.all()
        return render(
            request,
            'transaction_create.html',
            {
                'errors': errors,
                'context': {
                    'types': TRANSACTION_TYPES,
                    'locations': locations,
                    'products': products,
                    'formset': formset,
                }
            }
        )


# LOCATIONS

@login_required
def location_index(request):
    locations = Location.objects.all()

    return render(
        request,
        'location_index.html',
        context={'locations': locations}
    )


@login_required
def location_create(request):
    errors = None
    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['locations'] = json.dumps(
                list(Location.objects.values('id', 'name')))
            return redirect('product:location_index')
        else:
            errors = form.errors.as_data()
    else:
        form = CreateProductForm()

    return render(
        request,
        'location_create.html',
        {
            'form': form,
            'errors': errors,
        }
    )


@login_required
def location_edit(request, location_id):
    errors = None
    location = get_object_or_404(Location, id=location_id)

    if request.method == 'POST':
        form = LocationForm(request.POST, instance=location)
        form.save()
        request.session['locations'] = json.dumps(
            list(Location.objects.values('id', 'name')))
        return redirect('product:location_index')

    return render(
        request,
        'location_edit.html',
        {
            'location': location,
            'errors': errors
        }
    )


# REPORTES
@login_required
def xls_transactions(request):
    if request.user.location is None:
        cab = TransactionCab.objects.all()
    else:
        cab = TransactionCab.objects.distinct().filter(
            details__location=request.user.location)

    data = [
        [
            'ID',
            'Fecha',
            "Comentario",
            "Almacén",
            "Transacción",
            "Producto",
            "Cantidad"
        ]
    ]
    for item in cab:
        for detail in item.details.values('product__name', 'type', 'location__name', 'amount'):
            data.append([
                item.id,
                item.date.strftime("%d/%m/%Y"),
                item.comment,
                detail['location__name'],
                TRANSACTION_TYPES[detail['type']],
                detail['product__name'],
                int(detail['amount'])
            ])

    return ExcelResponse(data, 'Transacciones')


@login_required
def xls_products(request):
    data = [
        [
            'ID',
            "Almacén",
            'Producto',
            "Cantidad"
        ]
    ]
    products = Product.objects.all().order_by('-id')
    location_name = "-Todos-"
    if request.user.location is not None:
        location_name = request.user.location.name
    for product in products:
        if request.user.location is not None:
            stock = TransactionDet.objects.filter(
                location=request.user.location, product=product).aggregate(Sum('amount'))['amount__sum']
        else:
            stock = TransactionDet.objects.filter(
                product=product).aggregate(Sum('amount'))['amount__sum']
            
        if stock is None:
            stock = 0

        data.append([
            product.id,
            location_name,
            product.name,
            stock
        ])

    return ExcelResponse(data, 'Productos')

inventory/templates/details.html
{% extends 'base.html' %} {% block content %}

<div>
  <h6>{{ product.name }}</h6>
  <p>{{ product.category }}</p>
  <p>{{ product.stock }}</p>
  <p>{{ product.created_at }}</p>
</div>

{% endblock %}

inventory/templates/location_create.html
{% extends 'base.html' %} {% block content %}

<h1 class="mt-3">Almacén Nuevo</h1>

<div class="card mt-3">
    <div class="card-body">
        <form action="{% url 'product:location_create' %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="name" class="form-label">Nombre</label>
                <input type="text" class="form-control {% if errors.name %}is-invalid{% endif %}" name="name" id="name"
                    placeholder="..." required>
                <div class="invalid-feedback">
                    {% if errors.name %}
                    {% for error in errors.name %}
                    {{ error.message }}
                    {% endfor %}
                    {% endif %}
                </div>
            </div>

            <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Guardar</button>
            <a href="{% url 'product:location_index' %}" class="btn btn-outline-secondary"><i class="fa fa-undo"></i> Volver</a>
        </form>
    </div>
</div>

{% endblock %}

inventory/templates/location_edit.html
{% extends 'base.html' %} {% block content %}

<h1 class="mt-3">Almacén {{ location.name }}</h1>

<div class="card mt-3">
    <div class="card-body">
        <form action="{% url 'product:location_edit' location.id %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="name" class="form-label">Nombre</label>
                <input type="text" class="form-control {% if errors.name %}is-invalid{% endif %}" name="name" id="name"
                    placeholder="..." required value="{{ location.name }}">
                <div class="invalid-feedback">
                    {% if errors.name %}
                    {% for error in errors.name %}
                    {{ error.message }}
                    {% endfor %}
                    {% endif %}
                </div>
            </div>

            <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Guardar</button>
            <a href="{% url 'product:location_index' %}" class="btn btn-outline-secondary"><i class="fa fa-undo"></i>
                Volver</a>
        </form>
    </div>
</div>

{% endblock %}

inventory/templates/location_index.html
{% extends 'base.html' %} {% block content %}
{% load static %}

<h1 class="mt-3">Almacenes</h1>

<div class="card mt-3">
    <div class="card-body">
        <div class="row">
            <div class="col-md-3 mb-3 clearfix">
                <a class="btn btn-outline-primary" href="{% url 'product:location_create' %}">
                    <i class="fa fa-plus"></i> Nuevo</a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 table-responsive">
                <table class="table table-striped table-bordered" id="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for location in locations %}
                        <tr>
                            <td>{{ location.id }}</td>
                            <td>
                                <a href="{% url 'product:location_edit' location.id %}">
                                    {{ location.name }}
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    let table
    $(document).ready(function () {
        table = $("#table").DataTable({
            'language': {
                url: "{% static 'json/es-ES.json' %}"
            }
        })
    })
</script>

{% endblock %}

inventory/templates/product_create.html
{% extends 'base.html' %} {% block content %}

<h1 class="mt-3">Producto Nuevo</h1>

<div class="card mt-3">
    <div class="card-body">
        <form action="{% url 'product:create' %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="name" class="form-label">Nombre</label>
                <input type="text" class="form-control {% if errors.name %}is-invalid{% endif %}"
                    name="name" id="name" placeholder="..." required>
                <div class="invalid-feedback">
                {% if errors.name %}
                {% for error in errors.name %}
                    {{ error.message }}
                {% endfor %}
                {% endif %}       
                </div>
            </div>

            <div class="mb-3">
                <label for="stock" class="form-label">Stock</label>
                <input type="number" class="form-control {% if errors.name %}is-invalid{% endif %}" 
                    name="stock" id="stock" placeholder="0.00" required>
                <div class="invalid-feedback">
                {% if errors.stock %}
                {% for error in errors.stock %}
                    {{ error.message }}
                {% endfor %}
                {% endif %}       
                </div>
            </div>
            
            <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Guardar</button>
            <a href="{% url 'product:index' %}" class="btn btn-outline-secondary"><i class="fa fa-undo"></i> Volver</a>
        </form>
    </div>
</div>

{% endblock %}

{% block custom_js %}
<script>
    $(document).ready(function(){
        user_location = "{{ request.user.location.id|escapejs }}" ?? null
        console.log(user_location)
        if(user_location == "")
        {
            Swal.fire('Aviso', 'Antes de guardar un producto debe seleccionar un almacen predeterminado para su usuario', 'warning').then(assignLocation())
        }
    })
</script>
{% endblock %}

inventory/templates/product_edit.html
{% extends 'base.html' %} {% block content %}

<h1 class="mt-3">{{ product.name }}</h1>

<div class="card mt-3">
    <div class="card-body">
        <form action="{% url 'product:edit' product.id %}" method="POST">
            {% csrf_token %}

            <div class="mb-3">
                <label for="name" class="form-label">Nombre</label>
                <input type="text" class="form-control {% if errors.name %}is-invalid{% endif %}"
                    name="name" id="name" placeholder="..." required value="{{ product.name }}">
                <div class="invalid-feedback">
                {% if errors.name %}
                {% for error in errors.name %}
                    {{ error.message }}
                {% endfor %}
                {% endif %}       
                </div>
            </div>

            <div class="mb-3">
                <label for="stock" class="form-label">Stock</label>
                <input type="number" class="form-control {% if errors.name %}is-invalid{% endif %}" 
                        id="stock" placeholder="0.00" value="{{ product.stock }}" disabled>
            </div>

            <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Guardar</button>
            <a href="{% url 'product:index' %}" class="btn btn-outline-secondary"><i class="fa fa-undo"></i> Volver</a>
        </form>
    </div>
</div>


{% endblock %}

inventory/templates/product_form.html
{% extends 'base.html' %} {% block content %}
<form action="{% url 'product:create' %}" method="post" novalidate>
  {% csrf_token %} {{ form }}
  <input type="submit" value="Enviar" />
</form>
{% endblock %}

inventory/templates/product_index.html
{% extends 'base.html' %} {% block content %}
{% load static %}

<h1 class="mt-3">Productos</h1>

<div class="card mt-3">
  <div class="card-body">
    <div class="row">
      <div class="col-6 mb-3 clearfix">
        <a class="btn btn-outline-primary" href="{% url 'product:create' %}">
          <i class="fa fa-plus"></i> Nuevo</a>
      </div>
      <div class="col-6 text-end mb-3 clearfix">
        <a class="btn btn-outline-success" href="{% url 'product:xls_products' %}">
          <i class="fa fa-file-excel-o"></i> Exportar a Excel
        </a>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-12 table-responsive">
        <table class="table table-striped table-bordered" id="table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Stock</th>
            </tr>
          </thead>
        
          <tbody>
            {% for product in products %}
            <tr>
              <td>{{ product.id }}</td>
              <td>
                <a href="{% url 'product:edit' product.id %}">
                  {{ product.name }}
                </a>
              </td>
              <td>{{ product.stock }}</td>
              <!-- <td>{{ product.category }}</td> -->
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
  let table
  $(document).ready(function () {
    // Load Datatable
    table = $("#table").DataTable({
      language: {
        url: "{% static 'json/es-ES.json' %}"
      },
      sorting: [[0, 'desc']]
    })

    // Load Canvas

  })
</script>

{% endblock %}

inventory/templates/transaction_index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="mt-3">Transacciones</h1>

<secction class="container">
    <div class="card">
        <div class="card-body">

            <div class="row">
                <div class="col-6 mb-3 clearfix">
                  <a class="btn btn-outline-primary" href="{% url 'product:transaction_create' %}">
                    <i class="fa fa-plus"></i> Nueva
                  </a>
                </div>
                <div class="col-6 text-end mb-3 clearfix">
                  <a class="btn btn-outline-success" href="{% url 'product:xls_transactions' %}">
                    <i class="fa fa-file-excel-o"></i> Exportar a Excel
                  </a>
                </div>
              </div>

            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped table-sm align-middle" id="table" style="width: 100%;">
                        <thead>
                            <tr style="border-style: solid black 1px;">
                                <th>ID</th>
                                <th>Fecha</th>
                                <th>Comentario</th>
                                <th>
                                  <table class="table table-sm">
                                    <thead>
                                      <tr>
                                        <th class="text-center">Almacén</th>
                                        <th class="text-center">Producto</th>
                                        <th class="text-center">Transacción</th>
                                        <th class="text-center">Cantidad</th>
                                      </tr>
                                    </thead>
                                  </table>
                                </th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</secction>

<script>
   let transaction_types = undefined
    $(document).ready(function () {
      table = $("#table").DataTable({
        language: {
          url: "{% static 'json/es-ES.json' %}"
        },
        /*dom: 'Bfrtip',
        buttons: [
          'copyHtml5',
          {
            text: 'Excel',
            action: (e, dt, node, config) => {
              return window.location.href = "{% url 'product:xls_transactions' %}"
            }
          },
        ],*/
        responsive: true,
        ajax: {
            type: 'GET',
            url: '{% url "product:ajax_transactions" %}',
            dataSrc: (json) => {
              transaction_types = json.transaction_types;
              return json.data;
            }
        },
        columns: [
          { data: 'id' },
          { data: 'date' },
          { data: 'comment' },
          { 
            data: 'details', render: (d,t,r) => {
              let rows = ''
              d.forEach( (e) => {
                rows += `<tr>
                  <td class="text-center" width="25%">${e.location__name}</td>
                  <td class="text-start" width="25%"><b>${e.product__name}<b/></td>
                  <td class="text-center" width="25%">${transaction_types[e.type]}</td>
                  <td class="text-end" width="25%">${e.amount}</td>
                </tr>`
              });
              return `<table class="table table-sm m-0 table-bordered">${rows}</table>`;
            }
          },
          
        ],
        columnDefs: [
          { targets: '_all', className: 'text-center'},
          { targets: [-1, -2], orderable: false }
        ],
        sorting: [
          [1, 'desc'],
          [0, 'desc'],
        ]
      });
    })
  </script>

{% endblock %}

{% block custom_css %}
<!-- Responsive Datatable CSS -->
<link rel="stylesheet" href="{% static 'css/responsive.bootstrap5.min.css'%}">
<!-- Export Buttons -->
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.bootstrap5.min.css">
{% endblock %}

{% block custom_js %}
<!-- Basic Datatables Js -->
<script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/responsive.bootstrap5.min.js' %}"></script>
<!-- Export Buttons -->
<!-- <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.bootstrap5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js"></script> -->
{% endblock %}