erikamodas/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path("admin/", admin.site.urls),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path("inventory/", include('inventory.urls')),
    path('assign-location', views.assign_location, name='assign_location'),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # Products
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:product_id>', views.details, name='details'),
    path('<int:product_id>/edit', views.edit, name='edit'),
    # Transactions
    path('transactions/', views.transaction_index, name='transaction_index'),
    path('transactions/create', views.transaction_create, name='transaction_create'),
    path('ajax/transactions', views.ajax_transactions, name='ajax_transactions'),
    # Locations
    path('locations/', views.location_index, name='location_index'),
    path('locations/create', views.location_create, name='location_create'),
    path('locations/<int:location_id>/edit', views.location_edit, name='location_edit'),
    # Reports
    path('xls/transactions/', views.xls_transactions, name='xls_transactions'),
    path('xls/products/', views.xls_products, name='xls_products'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <!-- Datatables -->
  <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}">
  <!-- Fontawesome -->
  <link rel="stylesheet" href="{% static 'css/font-awesome-v4.css' %}">
  <!-- Jquery -->
  <script src="{% static 'js/jquery-3.7.0.js' %}"></script>
  <!-- Extras CSS -->
  {% block custom_css %}
  {% endblock %}
  <title>Inventario</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
      {% if user.is_authenticated %}
      <a class="navbar-brand" href="javascript:void(0);" id="select_location">Almacén: <span class="text-warning">
          {% if user.location %}{{ user.location }}{% else %}-Todos-{% endif %}</span>
      </a>
      {% endif %}
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-link" aria-current="page" href="{% url 'home' %}">Inicio</a>
          <a class="nav-link" href="{% url 'product:location_index' %}">Almacenes</a>
          <a class="nav-link" href="{% url 'product:index' %}">Productos</a>
          <a class="nav-link" href="{% url 'product:transaction_index' %}">Transacciones</a>
          {% endif %}
        </div>
      </div>
      <div class="d-flex">
        {% if user.is_authenticated %}
        <a class="btn btn-light btn-sm" href="{% url 'logout' %}"><b>Cerrar Sesión</b></a>
        {% else %}
        <a class="nav-link" href="{% url 'signin' %}">Iniciar Sesión</a>
        {% endif %}
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>
  <div class="container">{% block content %} {% endblock %}</div>
  <!-- Bootstrap -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <!-- Datatable -->
  <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
  <script src="{% static 'js/sweetalert.js' %}"></script>
  <script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
  </script>
  {% block messages %}
  {% for m in messages %}
  <script>Swal.fire('Aviso', m, 'info')</script>
  {% endfor %}
  {% endblock %}

  {% block custom_js %}
  {% endblock %}

  <script>
    // Selecciona el almacen del usuario en sesión
    $(document).ready(function () {
      $("#select_location").click(function () {
        assignLocation()
      })
    })

    function assignLocation() {
      const locations = JSON.parse("{{ request.session.locations|escapejs }}")
      let options = { "0": "-Todos-" }
      locations.forEach((e, i) => {
        options[e.id] = e.name
      })
      Swal.fire({
        title: 'Selector de Almacén',
        text: 'Seleccione el almacén predeterminado de sus operaciones',
        icon: "info",
        input: 'select',
        inputOptions: options,
        inputPlaceholder: "-Seleccione el almacén-",
        showCancelButton: true,
        cancelButtonText: '<i class="fa fa-undo"></i> Cancelar',
        cancelButtonColor: "#6c757d",
        confirmButtonText: '<i class="fa fa-save"></i> Aceptar',
        confirmButtonColor: "#0d6efd",
        showLoaderOnConfirm: true,
        preConfirm: async (option) => {
          try {
            console.log(option)
            if (option == "") return swal.showValidationMessage(`Debe seleccionar un almacen a asignar como predeterminado.`)
            $.ajax({
              type: 'GET',
              data: { location_id: option },
              url: "{% url 'assign_location' %}",
              success: (resp) => {
                if (resp.result == true) {
                  return Swal.fire('Aviso', 'Proceso realizado', 'success').then(() => window.location.reload())
                } else {

                }
              },
              error: () => {
                return swal.showValidationMessage(`El almacen no pudo ser asignado, intente nuevamente.`)
              }
            })
          } catch (error) {
            Swal.showValidationMessage(`Request failed: ${error}`);
          }
        },
        allowOutsideClick: () => !Swal.isLoading()
      }).then((resp) => {
      })
    }
  </script>
</body>

</html>

templates/form_snippet.html
{% load add_attr %}

{% for field in form %}
    <div class="mb-3">
    {{ field.label_tag }} 
    {% if field.errors %}
        {{ field|add_attr:"class:is-invalid" }}
    {% else %}
        {{ field }}
    {% endif %}
        <div class="invalid-feedback">
        {% for error in field.errors %}
            {{ error }}
        {% endfor %}
        </div>
    </div>
{% endfor %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="container">
    <div class="card text-start mt-3">
        <!-- <img class="card-img-top" src="holder.js/100px180/" alt="Title" /> -->
        <div class="card-body">
            <h4 class="card-title">Datos del Inventario</h4>
            <div class="row">
                <div class="col">
                    <div id="chart_products" style="width: 100%; height: 360px;"></div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col">
                    <div id="chart_locations" style="width: 100%; height: 360px;"></div>
                </div>
            </div>
        </div>
    </div>

</section>
<script>
    window.onload = function () {
        var chart_products = new CanvasJS.Chart("chart_products", {
            animationEnabled: true, // change to false
            title: {
                text: "{{ context.products.title | safe }}"
            },
            data: [{
                type: "column",
                dataPoints: {{ context.products.data | safe }}
            }]
        });
        chart_products.render();

        var chart_locations = new CanvasJS.Chart("chart_locations", {
            animationEnabled: true,
            exportEnabled: false,
            theme: "light1", //"light1", "dark1", "dark2"
            title: {
                text: "{{ context.locations.title | safe }}"
            },
            axisY: {
                interval: 10,
                suffix: "%"
            },
            toolTip: {
                shared: true
            },
            legend: {
                cursor: "pointer",
                itemclick: toggleDataSeries
            },
            data: {{ context.locations.data | safe }}
        })
        chart_locations.render();
    }

    function toggleDataSeries(e) {
        if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
            e.dataSeries.visible = false;
        } else {
            e.dataSeries.visible = true;
        }
        e.chart.render();
    }
</script>
{% endblock content %}

{% block custom_js %}
<script src="{% static 'plugins/canvas.min.js' %}"></script>
{% endblock custom_js %}

templates/signin.html
{% extends 'base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form action="/signin/" method="post" class="card card-body">
                {% csrf_token %}

                <h1 class="text-center">Iniciar Sesión</h1>
                {{ error }}
                {% csrf_token %}

                <!-- {{ form }} -->
                <div class="mb-3">
                    <label class="form-label" for="username">Usuario:</label>
                    <input type="text" name="username" id="username" placeholder="Ingrese su usuario"
                        class="form-control">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="password">Contraseña:</label>
                    <input type="password" name="password" id="password" placeholder="Ingrese su contraseña"
                        class="form-control">
                </div>

                <button class="btn btn-primary">
                    Signin
                </button>

            </form>
        </div>
    </div>
</main>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}

<main class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4 mt-5">
            <form action="" method="POST" class="card card-body">
                <h1 class="text-center">Signup</h1>
                {{ error }}
                {% csrf_token %}

                <!-- {{ form }} -->
                <div class="mb-3">
                    <label class="form-label" for="username">Username:</label>
                    <input type="text" name="username" id="username" placeholder="Writer your username"
                        class="form-control">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="password1">Password:</label>
                    <input type="password" name="password1" id="password1" placeholder="Writer your password"
                        class="form-control">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="password2">Confirm your Password:</label>
                    <input type="password" name="password2" id="password2" placeholder="Confirm your password"
                        class="form-control">
                </div>
                <button class="btn btn-primary">
                    Signup
                </button>
            </form>
        </div>
    </div>
</main>
{% endblock %}